[project]
name = "spacy-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pip>=25.0.1",
    "scikit-learn>=1.6.1",
    "spacy>=3.8.4",
    "spacytextblob>=5.0.0",
]
